name: DynamicSlots
main: com.github.neapovil.dynamicslots.DynamicSlots
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/dynamic-slots
depend:
  - CommandAPI
permissions:
  dynamicslots.command:
    default: op
